name: CombatLogger
description: Simple plugin that allows you to punish combat loggers! (Updated for latest PMMP Builds.)
author: VMPE Development Team
main: jacknoordhuis\combatlogger\CombatLogger
version: 0.0.5
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
